# Generated by Django 5.0.3 on 2024-06-06 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Trabalhos_aceitos',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Trabalhos_feitos',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
