# Generated by Django 5.0.3 on 2024-06-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0002_usuario_trabalhos_aceitos_usuario_trabalhos_feitos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materias_clas',
            new_name='Materias_class',
        ),
        migrations.RenameModel(
            old_name='Transações',
            new_name='Transacao',
        ),
    ]
