# Generated by Django 5.0.3 on 2024-06-16 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0003_rename_materias_clas_materias_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='materias_class',
            name='materias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socorro_app.cursos_class'),
        ),
    ]
