# Generated by Django 5.0.3 on 2024-06-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0005_materias_class_pai_alter_materias_class_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhos_fazer',
            name='curso_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='socorro_app.cursos_class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabalhos_fazer',
            name='trabalho',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabalhos_fazer',
            name='trabalho_cm_fazer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabalhos_fazer',
            name='trabalho_cm_pronto',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
