# Generated by Django 5.0.3 on 2024-06-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0009_remove_trabalhos_fazer_trabalho_cm_fazer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhos_fazer',
            name='quem_fez',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='socorro_app.trabalhos_fazer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socorro_app.usuario')),
            ],
            options={
                'unique_together': {('user', 'trabalho')},
            },
        ),
    ]
