# Generated by Django 5.0.3 on 2024-06-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0010_trabalhos_fazer_quem_fez_voto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='voto',
        ),
    ]
