# Generated by Django 5.0.3 on 2024-06-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0011_delete_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhos_fazer',
            name='quem_fez',
            field=models.FloatField(),
        ),
    ]
