# Generated by Django 5.0.3 on 2024-06-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0012_alter_trabalhos_fazer_quem_fez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhos_fazer',
            name='pago',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trabalhos_fazer',
            name='valor_afazer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor_pago',
            field=models.FloatField(),
        ),
    ]
