# Generated by Django 5.0.3 on 2024-06-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0013_alter_trabalhos_fazer_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhos_fazer',
            name='trabalho_cm_pronto',
            field=models.FileField(upload_to='pronto/'),
        ),
    ]
