# Generated by Django 5.0.3 on 2024-06-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0016_remove_trabalhos_fazer_arquivo_trabalhoarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhos_fazer',
            name='quem_compro',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
