# Generated by Django 5.0.3 on 2024-06-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socorro_app', '0017_trabalhos_fazer_quem_compro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabalhos_fazer',
            old_name='quem_compro',
            new_name='quem_pago',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='quem_pago',
            new_name='quem_vendeu',
        ),
    ]
